/*export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  GET_USER: "GET_USER_SUCCESS",

  LOGOUT: "USER_LOGOUT",

  EDIT_PROFILE: "USER_EDIT_PROFILE",
};*/
